---
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flickr_upload
    environment:
      API_KEY: MY_KEY
      API_SECRET: MY_SECRET
      API_TOKEN: MY_TOKEN
      API_TOKEN_SECRET: MY_TOKEN_SECRET
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command:
      - -u
      - /app/web.py

  mail:
    build:
      context: .
      dockerfile: Dockerfile
    image: flickr_upload
    environment:
      API_KEY: MY_KEY
      API_SECRET: MY_SECRET
      API_TOKEN: MY_TOKEN
      API_TOKEN_SECRET: MY_TOKEN_SECRET
      EMAIL_USER: MY_ACCOUNT@gmail.com
      EMAIL_PASSWORD: MY_PASSWORD
      EMAIL_IMAP: imap.gmail.com
    command:
      - -u
      - /app/mail.py